### ISSUE TITLE
FoxGlow is not compatible with newer ColoredGlow Lib (2.0.0 and 2.0.1 tested)

### ISSUE THREAD

**Issue by ghost** [Emafire003/FoxGlow#6]
Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'foxglow'!
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4) ~[?:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.9.jar:?]
	at net.minecraft.server.Main.main(Main:101) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [minecraft_server.jar:0.11.0]
Caused by: java.lang.IncompatibleClassChangeError: Expected static method 'void me.emafire003.dev.coloredglowlib.ColoredGlowLib.setPerEntityTypeColor(boolean)'
	at me.emafire003.dev.foxglow.FoxGlow.onInitialize(FoxGlow.java:29) ~[FoxGlow-1.4.0.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.9.jar:?]
	... 8 more

**And this error comes from the newest Lib version on server:**
[20:46:44] [Server thread/INFO]: Getting variables values from the data file...
[20:46:44] [Server thread/ERROR]: There was an error while reading on the file
[20:46:44] [Server thread/INFO]: [STDERR]: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 2 path $
[20:46:44] [Server thread/INFO]: [STDERR]: 	at com.google.gson.Gson.fromJson(Gson.java:975)
[20:46:44] [Server thread/INFO]: [STDERR]: 	at com.google.gson.Gson.fromJson(Gson.java:928)
[20:46:44] [Server thread/INFO]: [STDERR]: 	at com.google.gson.Gson.fromJson(Gson.java:877)
[20:46:44] [Server thread/INFO]: [STDERR]: 	at me.emafire003.dev.coloredglowlib.util.DataSaver.getDefaultColor(DataSaver.java:190)
[20:46:44] [Server thread/INFO]: [STDERR]: 	at me.emafire003.dev.coloredglowlib.ColoredGlowLib.getValuesFromFile(ColoredGlowLib.java:186)
[20:46:44] [Server thread/INFO]: [STDERR]: 	at me.emafire003.dev.coloredglowlib.ColoredGlowLib.lambda$new$1(ColoredGlowLib.java:56)
[20:46:44] [Server thread/INFO]: [STDERR]: 	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$2(ServerLifecycleEvents.java:49)
[20:46:44] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.handler$edj000$afterSetupServer(MinecraftServer.java:13801)
[20:46:44] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644)
[20:46:44] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
[20:46:44] [Server thread/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[20:46:44] [Server thread/INFO]: [STDERR]: Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 2 path $
[20:46:44] [Server thread/INFO]: [STDERR]: 	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:824)
[20:46:44] [Server thread/INFO]: [STDERR]: 	at com.google.gson.internal.bind.TypeAdapters$15.read(TypeAdapters.java:380)
[20:46:44] [Server thread/INFO]: [STDERR]: 	at com.google.gson.internal.bind.TypeAdapters$15.read(TypeAdapters.java:368)
[20:46:44] [Server thread/INFO]: [STDERR]: 	at com.google.gson.Gson.fromJson(Gson.java:963)
[20:46:44] [Server thread/INFO]: [STDERR]: 	... 10 more

**Comment by Emafire003** [comment]
I know it's not, those versions added a "breaking" change, so you should stick to older versions for now. I am working on a new release, should take at least 1 day for the fabric release and a bit more for the forge port

**Comment by Emafire003** [comment]
Update: a few issues have come up, and they are a bit tricky to fix. So it'll be a couple more days.

**Comment by ghost** [comment]
Alright 😊
